### ISSUE TITLE
Is there still an interest for a mailing list for Eventum?

### ISSUE THREAD

**Issue by infracritical** [eventum/eventum#292]
I house and operate several mailing lists on a dedicated server.

The reason for asking this question is that there was supposed to be both an end-user and developer version of the mailing list.

I am offering services sum gratis -- a.k.a.; free, zilch, nil, nonilla, zoppo, zero.  IMHO, this is one way of helping and giving back to the community.

Is there any interest, or have you resorted to using only GitHub as the method of communicating via email?  Please let me know: bob@infracritical.com, or reply to this posting.

Thx.

**Comment by glensc** [comment]
there's no work being done on mailing lists, because haven't been able to obtain current archives. altho no priorities on that. the email addresses should still work, but there's no gmane archive anymore.

see https://github.com/eventum/eventum/pull/191

also i see the community is not that big that mailing lists is needed.

**Comment by cpinfold** [comment]
There are some development conversations that happen on Gitter:

https://gitter.im/eventum/eventum

The mailing lists used to be good for announcing releases and resolving
issues.. that was before GitHub.

Craig.
