### ISSUE TITLE
Deleting issues

### ISSUE THREAD

**Issue by infracritical** [eventum/eventum#297]
There's *got* to be a way to delete issues; in this case, I've created several *test* issues, and now would like to delete them, reset the issuance back to the original issue ID before all of the test issues were initiated.

I've found this URL, https://github.com/eventum/eventum/wiki/System-Advanced:-Deleting-Issues, outlining that it's impossible to delete an issue via the user interface.  Why?  If you're the site administrator, I would think that it should be possible to delete an issue simply based on providing an issue ID number, then simply delete the record from within the database.

So...is this possible?

**Comment by cpinfold** [comment]
I created a deleted issues project and just move the ones I don't want
there.

Craig

**Comment by glensc** [comment]
if you want to start from scratch, create new database instead.

however, if you're still interested in "delete issues" script [outlined in wiki](https://github.com/eventum/eventum/wiki/System-Advanced:-Deleting-Issues), i could create updated version that works with current eventum.

the official support was removed because eventum principle is soft delete (altho that doesn't apply everywhere).

**Comment by glensc** [comment]
actually, seems the script already exists: [contrib/delete_issues.php](../tree/master/contrib/delete_issues.php)

**Comment by glensc** [comment]
updated wiki: https://github.com/eventum/eventum/wiki/System-Advanced:-Deleting-Issues
