### ISSUE TITLE
changes to Initial Description are sent in html mail

### ISSUE THREAD

**Issue by glensc** [eventum/eventum#36]
found another regression:

when I update `Initial Description` area in issue, then email that gets sent out to notification list, contains `<br>` at the end of the each "old" line:

```
Changed Fields:
----------------------------------------------------------------------
Description:
@@ -1,61 +1,61 @@
-overall status:<br />
+overall status:

```

**Comment by glensc** [comment]
any ideas what was cause of this? i.e what made the iss_description as html

as the line you changed is very old 89357887

**Comment by balsdorf** [comment]
It probably has done that for a long time. Internally we almost never
update the issue description so we wouldn't have noticed it.

The issue is iss_description
https://github.com/eventum/eventum/blob/master/lib/eventum/class.issue.php#L3008
has nl2br run on it, which is stupid but I didn't have time to go through
and change that.

On Mon, Mar 2, 2015 at 1:10 PM, Elan Ruusamäe <notifications@github.com>
wrote:

> any ideas what was cause of this? i.e what made the iss_description as html
>
> as the line you changed is very old 8935788
> <https://github.com/eventum/eventum/commit/89357887ac8a696a4bbe2a6399b4ce20c5ae39e6>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/issues/36#issuecomment-76785275>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com
