### ISSUE TITLE
Does Eventum version 2.1.1 operate on Windows  2012 or later?

### ISSUE THREAD

**Issue by cohuser** [eventum/eventum#709]
Does Eventum version 2.1.1 operate on Windows 2012 or later? 
Thanks

**Comment by glensc** [comment]
Eventum does not have any special requirements aside from php and webserver.

**Comment by cohuser** [comment]
Thank you for the info. Which is the oldest version that is supported?

**Comment by glensc** [comment]
I can't say that there even exists support of any version. There's no commercial entity behind the project.

However, the update procedure is the same since 3.2.0:

- https://github.com/eventum/eventum/blob/v3.8.5/docs/wiki/Upgrading.md

but do read each version release notes, go down to version the update requires, as they indicate since what version they support update from, and what new requirements exists (php version for example).

**Comment by cohuser** [comment]
Thanks
