### ISSUE TITLE
Release field blocked in red

### ISSUE THREAD

**Issue by plindry** [eventum/eventum#89]
Hello,

I've intalled a 3.0.2 versión from scratch. I've created several Releases. When i create an issue and i want update it the reléase field is blocked. I entered with the admin user and i can't update it in this field. I've reviewed the configuration but i don't know where to change this behaviour. We used 2.3.6 for several years and we can change this field as developers.

Any one can help me?
Regards 
Antonio

**Comment by glensc** [comment]
why 3.0.2, latest is 3.0.5?

you're not the first one going for 3.0.2, even there are more releases out! i wonder is there reason for that.

**Comment by balsdorf** [comment]
Hi Antonio,

Looks like when we made some major changes to the update page a few releases back the code for scheduled releases was removed accidentally. I've added it back and it will be included in our next release.  I'm not sure when this will be so you have a couple of options: 
* Apply the changes in the patch manually. This may or may not work depending on what other changes have been made since 3.0.2
* Download the development version and use that.
* Wait for the next release.

I run the development version in production without any issues so you should be good but the other options should be good. @glensc might comment on when he expects to do the next release.

**Comment by plindry** [comment]
Thank you balsdorf. I will try the development version. We are using eventum for eight years and we decided to change to a newer version. I'm testing this new versions so no problem to try with the development version.

glensc, i am testing with 3.0.2 version because it the one i downloaded one mounth ago. In the middle i have to work, attend my family, charge the version with all the parameters and personal fields with choises because i need to seem as much as posible as our previos version 2.2. It takes time but no problem to try the newer.

Regards 
Antonio

**Comment by glensc** [comment]
you could had just upgraded, then don't have to add fields to db, etc.

database migration is fully functional from 2.3.6. what is not, is if you modified templates. but with 2.4+ you can just use "local" templates aside "official" templates.

**Comment by plindry** [comment]
I forget to comment it but its the same problem with the group field. You can not change it but in previous versions you can

**Comment by plindry** [comment]
Our version is 2.2 not 2.3.6 as i said. No problem starting with a free installation for the new year.
Regards

**Comment by balsdorf** [comment]
Group field is now back as well. Thanks!

**Comment by plindry** [comment]
Thanks basldorf

**Comment by cmiller1111** [comment]
Hi there!  We're experiencing the same issue in 3.0.5.  I see you mentioned applying the patch, balsdorf, can you link me to instructions on how to do that?

**Comment by glensc** [comment]
it is included in 3.0.6 release
