### ISSUE TITLE
3.0.5: General Setup: Daily Tips?

### ISSUE THREAD

**Issue by poing** [eventum/eventum#90]
Checking out v3.0.5 and updating docs.  Found General Setup shows: "Display Description as Email #0" where "Daily Tips" should be.

Brian

**Comment by glensc** [comment]
@balsdorf wanna have look?

**Comment by balsdorf** [comment]
Not a bug. We removed daily tips over a year ago (#20) and Email 0 just happens to show up in that same place.

**Comment by poing** [comment]
Sorry, didn't notice this was closed.  The problem is, I have no idea what "Display Description as Email #0" is.  Is it a feature or function?  What does it do?

**Comment by glensc** [comment]
- "Daily Tips" - was  removed in #20 
- "Display Description as Email #0"  - new feature: 014f9bff3bd4c861bbcd4e2ab26140d55e548152

**Comment by poing** [comment]
I see it's a new feature.  Don't understand it, Bryan even mentioned it would be confusing in #1.  Looks like it uses ```iss_original_description``` as the message body.  ```if ($email_id == 0) {...}``` is the trigger, but not sure of the use case.  Bryan, so I can explain it on the wiki, can you help me understand it better?

**Comment by poing** [comment]
BTW: This was not really about "Daily Tips".  I originally thought the NEW setting was an artifact left behind form it's removal.

**Comment by balsdorf** [comment]
Sure, so "Use Description as email #0" means that in the email list at the
bottom of an issue there would be a new email at the top, #0 whose content
would be the issue description.

Our support engineers requested this so they could look at the whole issue
conversation in one spot, instead of having to scroll up the page.

On Tue, Jan 19, 2016 at 5:35 PM, Brian LaVallee <notifications@github.com>
wrote:

> BTW: This was not really about "Daily Tips". I originally thought the NEW
> setting was an artifact left behind form it's removal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventum/eventum/issues/90#issuecomment-173023451>.
>



-- 
Bryan Alsdorf
MariaDB Corporation | http://mariadb.com

**Comment by poing** [comment]
Thanks for the clarification.  Added the usage information to the wiki.
